name: Windows Installer

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      - name: Build Windows installer
        run: |
          npm run build:localize
          npm run build:electron
          npx electron-builder --win -p never
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: release/**
